
### get JWT Token
GET {{host}}:{{port}}/auth
Content-Type: application/json

{
  "username": "cos",
  "password": "cos"
}

> {%
client.log(response.body.jwtToken)
client.global.set("token", response.body.jwtToken);
%}

### get all assets for logged user
GET {{host}}:{{port}}/assets
Authorization: Bearer {{token}}


### post assets for logged user
POST {{host}}:{{port}}/assets
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "amount": 223.00,
    "category": "RENT",
    "description": "some house"
  },
  {
    "amount": 1223.00,
    "incomeDate": "2020-03-10T12:01:03.001Z",
    "category": "SALARY",
    "description": "some job"
  }
]

### get all rooms for logged user
GET {{host}}:{{port}}/rooms
Authorization: Bearer {{token}}

### get all suggest assets for logged user
GET {{host}}:{{port}}/suggest
Authorization: Bearer {{token}}


### update room for logged user
POST {{host}}:{{port}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "4f73f0af-f29c-445e-86e3-9e26c521b363",
  "type": "ROOM_S",
  "cost": 15.00
}


### get property for logged user
GET {{host}}:{{port}}/property
Authorization: Bearer {{token}}


### add property for logged user
POST {{host}}:{{port}}/property
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rooms": [],
  "single": false,
  "city": "Warszawa",
  "postCode": "02-020",
  "street": "Osiłka 1A/B",
  "house": "1"
}

### update property for logged user
PUT {{host}}:{{port}}/property
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "id": "6ebf7502-afde-40e9-8bc4-09b5b579a0ec",
  "rooms": [
    {
      "id": "3985565d-2da6-48f4-a011-601b9b9c3ed8",
      "type": "ROOM_XL",
      "cost": 50.00,
      "rent": true
    },
    {
      "id": "36e096c0-8586-44ec-96bd-7dbfb490ef8e",
      "type": "ROOM_M",
      "cost": 20.00,
      "rent": false
    }
  ],
  "single": false,
  "city": "Warszawa",
  "postCode": "02-020",
  "street": "Ważniak 12",
  "house": "12B"
}