
### get JWT Token
GET {{host}}:{{port}}/auth
Content-Type: application/json

{
  "username": "cos",
  "password": "cos"
}

> {%
client.log(response.body.jwtToken)
client.global.set("token", response.body.jwtToken);
%}

### Post upload assets
POST {{host}}:{{port}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="./AssetsCsvData.csv"

< ./AssetsCsvData.csv

### Post upload expenses
POST {{host}}:{{port}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="./ExpnesesCsvData.csv"

< ./ExpensesCsvData.csv

### get download assets with mays assets for logged user
GET {{host}}:{{port}}/download/assets
Authorization: Bearer {{token}}

### get download filtered assets with mays assets for logged user
GET {{host}}:{{port}}/download/assets/filter?month=february&year=2020&category=rent
Authorization: Bearer {{token}}

### get download expenses with mays assets for logged user
GET {{host}}:{{port}}/download/expenses
Authorization: Bearer {{token}}

### get months with mays assets for logged user
GET {{host}}:{{port}}/calendar/months/days
Authorization: Bearer {{token}}


### get all assets for logged user
GET {{host}}:{{port}}/assets
Authorization: Bearer {{token}}

### get all expenses for logged user
GET {{host}}:{{port}}/expenses
Authorization: Bearer {{token}}


### post assets for logged user
POST {{host}}:{{port}}/assets
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "amount": 223.00,
    "category": "RENT",
    "description": "some house"
  },
  {
    "amount": 1223.00,
    "incomeDate": "2020-03-10T12:01:03.001Z",
    "category": "SALARY",
    "description": "some job"
  }
]

### get all rooms for logged user
GET {{host}}:{{port}}/rooms
Authorization: Bearer {{token}}

### get all suggest assets for logged user
GET {{host}}:{{port}}/suggest
Authorization: Bearer {{token}}


### update room for logged user
POST {{host}}:{{port}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "4f73f0af-f29c-445e-86e3-9e26c521b363",
  "type": "ROOM_S",
  "cost": 15.00
}


### get property for logged user
GET {{host}}:{{port}}/property
Authorization: Bearer {{token}}


### add property for logged user
POST {{host}}:{{port}}/property
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rooms": [],
  "single": false,
  "city": "Warszawa",
  "postCode": "02-020",
  "street": "Osiłka 1A/B",
  "house": "1"
}

### update property for logged user
PUT {{host}}:{{port}}/property
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "id": "6ebf7502-afde-40e9-8bc4-09b5b579a0ec",
  "rooms": [
    {
      "id": "3985565d-2da6-48f4-a011-601b9b9c3ed8",
      "type": "ROOM_XL",
      "cost": 50.00,
      "rent": true
    },
    {
      "id": "36e096c0-8586-44ec-96bd-7dbfb490ef8e",
      "type": "ROOM_M",
      "cost": 20.00,
      "rent": false
    }
  ],
  "single": false,
  "city": "Warszawa",
  "postCode": "02-020",
  "street": "Ważniak 12",
  "house": "12B"
}


### add cyclical expenses for logged user
GET {{host}}:{{port}}/cyclical/expenses
Authorization: Bearer {{token}}


### post cyclical expenses for logged user
POST {{host}}:{{port}}/cyclical/expenses
Authorization: Bearer {{token}}
Content-Type: application/json


[
  {
    "amount": 200,
    "category": "FUN",
    "month": "MAY",
    "day": 21
  },
  {
    "amount": 2000,
    "category": "EDUCATION",
    "month": "MAY",
    "day": 11
  }
]


### get all assets for logged user
GET {{host}}:{{port}}/auditor/expenses/month/august/year/2020/estimate
Authorization: Bearer {{token}}

### post estimates
POST {{host}}:{{port}}/auditor/estimate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "FOR_LIFE": "60",
  "EDUCATION": "20",
  "FUN": "10",
  "OTHERS": "10"
}


### send mail
GET {{host}}:{{port}}/mail
Authorization: Bearer {{token}}

### send mail
POST {{host}}:{{port}}/additional/data
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "some@mail.com"
}


### send mail
GET {{host}}:{{port}}/currency/codes
Authorization: Bearer {{token}}
